=== ngothuonghoanganh/bookStore/dealSchema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="deal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:int" minOccurs="1" />
                <xs:element name="userId" type="xs:int" minOccurs="1" />
                <xs:element name="discountId" type="xs:int" minOccurs="0" />
                <xs:element ref="dealDetails" maxOccurs="unbounded" minOccurs="1"></xs:element>
                <xs:element name="discountCode" type="xs:string" minOccurs="0" />
                <xs:element name="discountPrice" type="xs:decimal" minOccurs="0" />
                <xs:element name="totalPrice" type="xs:decimal" minOccurs="1" />
                <xs:element name="createDate" type="xs:string" minOccurs="0" />
                <xs:element name="status" type="xs:string" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="dealDetail">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:int" minOccurs="1" />
                <xs:element name="bookId" type="xs:int" minOccurs="1" />
                <xs:element name="bookName" type="xs:string" minOccurs="1" />
                <xs:element name="quantity" type="xs:int" minOccurs="1" />
                <xs:element name="price" type="xs:decimal" minOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="dealDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dealDetail" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="deals">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="deal" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ngothuonghoanganh/bookStore/dealXML.xml
<deals xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:noNamespaceSchemaLocation="dealSchema.xsd">
	<deal>
		<id>1</id>
		<userId>1</userId>
		<discountId>1</discountId>
		<discountCode>VuiVeMuaSach</discountCode>
		<discountPrice>1.0</discountPrice>
		<totalPrice>50.0</totalPrice>
		<createDate>2021-06-13</createDate>
		<status>con hang</status>
	</deal>

	<deal>
		<id>2</id>
		<userId>1</userId>
		<discountId>2</discountId>
		<discountCode>KhuyenMai</discountCode>
		<discountPrice>1.0</discountPrice>
		<totalPrice>50.0</totalPrice>
		<createDate>2021-06-12</createDate>
		<status>con hang</status>
	</deal>
</deals>
